---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: helm-worpress-namespace
  namespace: tanzu-continuousdelivery-resources
spec:
  interval: 1m0s
  path: ./wordpress-helm
  prune: true
  sourceRef:
    kind: GitRepository
    name: ako-cluster
    namespace: tanzu-continuousdelivery-resources
