apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ako-release
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: default
  chart:
    spec:
      chart: ako
      sourceRef:
        kind: HelmRepository
        name: ako
      values:
        AKOSettings:
          clusterName: moodle-cluster
          layer7Only: true
        NetworkSettings:
          vipNetworkList:
          - networkName: tanzu-frontend
            cidr: 172.25.5.0/24
        L7Settings:
          serviceType: NodePort
        ControllerSettings:
          controllerHost: '172.25.2.241'
        avicredentials:
          username: 'admin'
          password: 'IPMipm10!'

