---
ingress:
  enabled: true
  virtual_host_fqdn: "prometheus-test.k8s.sc.ipm"
  prometheus_prefix: "/"
  alertmanager_prefix: "/alertmanager/"
  prometheusServicePort: 80
  alertmanagerServicePort: 80
prometheus:
  pvc:
    storageClassName: vsphere-tanzu
alertmanager:
  pvc:
    storageClassName: vsphere-tanzu
